#!/bin/bash

# Run test first
./script/test

build_dir="build"
entry_point="index.js"
target_point="d3-scroller"

rollup -c $1 -f umd -g d3-selection:d3,d3-drag:d3,d3-scale:d3,d3-transition:d3 -n d3 -o $build_dir/$target_point.js -- $entry_point
uglifyjs  $build_dir/$target_point.js -c negate_iife=false -m -o $build_dir/$target_point.min.js
